//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Producent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Indeks
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Pole wymagane")]
        public string Kod { get; set; }
        [Required(ErrorMessage = "Pole wymagane")]
        public string Nazwa { get; set; }
        [Required(ErrorMessage = "Pole wymagane")]

        public int RodzajIndeksuId { get; set; }
        [Required(ErrorMessage = "Pole wymagane")]

        public int JednostkaMiaryId { get; set; }
        public Nullable<decimal> CenaZakupu { get; set; }
        public Nullable<decimal> CenaSprzedazy { get; set; }
        public Nullable<decimal> Ciężar { get; set; }
        public bool CzyAktywny { get; set; }
        public bool CzyTechnologia { get; set; }
        public string IndeksDostawcy { get; set; }
        public string Opis { get; set; }
        public string OpisDostawcy { get; set; }
        public string KodKreskowy { get; set; }
        public Nullable<int> LiczbaDniDostawy { get; set; }
        public Nullable<decimal> StanMin { get; set; }
        public Nullable<decimal> StanMax { get; set; }
    
        public virtual JednostkaMiary JednostkaMiary { get; set; }
        public virtual RodzajIndeksu RodzajIndeksu { get; set; }
    }
}
