//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Producent.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProducentEntities : DbContext
    {
        public ProducentEntities()
            : base("name=ProducentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Indeks> Indeks { get; set; }
        public virtual DbSet<JednostkaMiary> JednostkaMiary { get; set; }
        public virtual DbSet<RodzajIndeksu> RodzajIndeksu { get; set; }
    }
}
